### PR TITLE
Compressed optical flow

### PR DESCRIPTION
**Pull request by sajidanower23**

### CODE REVIEW

**Comment by hjed** [comment]
There's already a PR for this?

**Comment by hjed** [comment]
Wrt to compression is this actually faster?
Given that both the cameras and this code run on the nuc, I'd expect compression to make it slower.

**Comment by YiweiHan** [comment]
rqt was quoting rates of ~0.5Hz for raw images, and ~4-5Hz for compressed images. then again we were running rqt on groundstation so that may have affected something

**Comment by hjed** [comment]
Yeah from the gs if you're subscribed to it there it will be much faster. But the oposite is true for the nuc.

**Comment by hjed** [comment]
But if you want to use compression you should use image transport http://wiki.ros.org/image_transport

**Comment by sajidanower23** [comment]
Closing this in favour of #124

**Pull request closed without merging**
